routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
	Route::get('', function(){
		return redirect()->route('admin.index');
	});

	Route::get('login', ['as' => 'show_login', 'uses' => 'Admin\AuthController@showLoginForm']);
	Route::post('login', ['as' => 'login', 'uses' => 'Admin\AuthController@login']);

	Route::get('new', ['as' => 'index', 'uses' => 'Admin\ApproveNewRestaurantsController@index']);
	Route::get('_ajax/restaurant_for_approbed/{restaurant_id}', ['as' => 'ajax.rta', 'uses' => 'Admin\ApproveNewRestaurantsController@get_restaurant']);
	Route::post('approve/{id}/new', ['as' => 'approve_restaurant', 'uses' => 'Admin\ApproveNewRestaurantsController@approve']);
	Route::post('deny/{id}/new', ['as' => 'deny_restaurant', 'uses' => 'Admin\ApproveNewRestaurantsController@deny']);

	Route::get('changes', ['as' => 'changes', 'uses' => 'Admin\ApproveRestaurantsChangesController@index']);
	Route::post('approve/{id}/changes', ['as' => 'approve_changes', 'uses' => 'Admin\ApproveRestaurantsChangesController@approve']);

	Route::post('logout', ['as' => 'logout', 'uses' => 'Admin\AuthController@logout']);
});

Route::group(['prefix' => 'c'], function() {
	Route::get('user/verify/{code}', 'VerifyUserController@verify');

	Route::get('user/reset/{token}', 'ResetPwdUserController@showResetForm')->name('c.user.reset');
	Route::post('user/reset', 'ResetPwdUserController@reset')->name('c.user.reset.post');

	Route::get('user/remail/{code}', 'ResetEmailUserController@index')->name('c.user.remail');
});

Route::group(['prefix' => 'manager'], function() {

	// Portada
	Route::get('/', ['as' => 'welcome', 'uses' => 'WelcomePageController@index']);

	// Auth
	Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
	Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
	Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
	Route::group(['prefix' => 'password', 'as' => 'password.'], function() {
		Route::get('reset', ['as' => 'request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
		Route::post('email', ['as' => 'email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
		Route::get('reset/{token}', ['as' => 'reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
		Route::post('reset', ['as' => 'reset', 'uses' => 'Auth\ResetPasswordController@reset']);
	});

	// Asistente de registro (Usuarios y Restaurantes)
	Route::group(['prefix' => 'assistant', 'as' => 'assistant.'], function() {
		Route::get('start', ['as' => 'start', 'uses' => 'Assistant\StartController@showRegistrationForm']);
		Route::post('start', ['as' => 'start.post', 'uses' => 'Assistant\StartController@register']);

		Route::get('create', ['as' => 'create', 'uses' => 'Assistant\CreateController@showRegistrationForm']);
		Route::post('create', ['as' => 'create.post', 'uses' => 'Assistant\CreateController@register']);

		// Peticiones ajax para jquery
		Route::group(['prefix' => '_ajax', 'as' => 'ajax.'], function() {
			Route::get('restaurantTags', ['as' => 'restaurant_tags', 'uses' => 'Assistant\CreateController@getRestaurantTags']);
		});
	});

	/* EMAIL TESTS
	Route::get('mail/view', function ()
	{
		return new App\Mail\UserWelcome();
	});
	*/

	// Administración
	Route::get('/home', 'HomeController@index')->name('home');

	Route::group(['prefix' => 'restaurant', 'as' => 'restaurant.'], function() {

		Route::post('{restaurant_id}/apr', ['as' => 'approve_request', 'uses' => 'RestaurantManage\HomeController@apr']);

		Route::get('{restaurant_id}', ['as' => 'index', 'uses' => 'RestaurantManage\HomeController@index']);

		Route::get('{restaurant_id}/reserves_in_day/{date}', ['as' => 'index.ajax.reserves_data', 'uses' => 'RestaurantManage\HomeController@ajax_reserves_in_day']);
		Route::get('{restaurant_id}/available_dates', ['as' => 'index.ajax.available_dates', 'uses' => 'RestaurantManage\HomeController@ajax_available_days']);
		
		Route::group(['prefix' => '{restaurant_id}/reserves', 'as' => 'reserves.'], function() {
			Route::get('', ['as' => 'index', 'uses' => 'RestaurantManage\ReservesController@index']);

			Route::group(['prefix' => '_ajax', 'as' => 'ajax.'], function() {
				Route::get('events', ['as' => 'get', 'uses' => 'RestaurantManage\ReservesController@ajax_get_events']);
				Route::post('create', ['as' => 'create', 'uses' => 'RestaurantManage\ReservesController@ajax_create_event']);
				Route::post('event/{event_code}/finalize', ['as' => 'finalize', 'uses' => 'RestaurantManage\ReservesController@ajax_finalize_event']);
				Route::post('event/{event_code}/cancel', ['as' => 'cancel', 'uses' => 'RestaurantManage\ReservesController@ajax_cancel_event']);

				Route::get('get_hours_of_date', ['as' => 'av_hours', 'uses' => 'RestaurantManage\ReservesController@ajax_get_hours']);
			});
		});

		Route::group(['prefix' => '{restaurant_id}/menu', 'as' => 'menu.'], function() {
			Route::get('', ['as' => 'index', 'uses' => 'RestaurantManage\MenuController@index']);
			Route::post('', ['as' => 'save', 'uses' => 'RestaurantManage\MenuController@save']);
		});

		Route::resource('{restaurant_id}/photos', 'RestaurantManage\PhotosController');

		Route::post('{restaurant_id}/schedulers/closed_day', ['as' => 'schedulers.closed_day.store', 'uses' => 'RestaurantManage\SchedulersController@closed_day_store']);
		Route::delete('{restaurant_id}/schedulers/closed_day/{cld_date}', ['as' => 'schedulers.closed_day.destroy', 'uses' => 'RestaurantManage\SchedulersController@closed_day_destroy']);
		Route::get('{restaurant_id}/schedulers/{sch_id}/organize', ['as' => 'schedulers.organize', 'uses' => 'RestaurantManage\SchedulersController@organize']);

		// Peticiones ajax para jquery
		Route::group(['prefix' => '{restaurant_id}/schedulers/{sch_id}/_ajax', 'as' => 'schedulers.ajax.'], function() {
			Route::post('sch_day/create', ['as' => 'sch_day.create', 'uses' => 'RestaurantManage\SchedulersController@ajax_create']);
			Route::post('sch_day/update', ['as' => 'sch_day.update', 'uses' => 'RestaurantManage\SchedulersController@ajax_update']);
			Route::post('sch_day/remove', ['as' => 'sch_day.remove', 'uses' => 'RestaurantManage\SchedulersController@ajax_remove']);
		});
		Route::resource('{restaurant_id}/schedulers', 'RestaurantManage\SchedulersController');

		Route::get('{restaurant_id}/statistics', ['as' => 'statistics', 'uses' => 'RestaurantManage\StatisticsController@index']);

		Route::group(['prefix' => '{restaurant_id}/settings', 'as' => 'settings.'], function() {
			Route::get('', ['as' => 'info', 'uses' => 'RestaurantManage\SettingsInfoController@index']);
			Route::put('', ['as' => 'info.save', 'uses' => 'RestaurantManage\SettingsInfoController@save']);

			Route::get('managers', ['as' => 'managers', 'uses' => 'RestaurantManage\SettingsManagersController@index']);
			Route::get('_ajax/users', ['as' => 'managers.ajax.get_users', 'uses' => 'RestaurantManage\SettingsManagersController@ajax_get_users']);
			Route::post('managers', ['as' => 'managers.save', 'uses' => 'RestaurantManage\SettingsManagersController@save']);
		});
		Route::get('c/{code}', ['as' => 'settings.managers.confirmation', 'uses' => 'RestaurantManage\SettingsManagersController@confirmation']);
	});
});

resources/views/admin/changes.blade.php
@extends('admin.structure')

@section('main_content')
@parent
<div class="card-list">
	@forelse ($restaurants as $indexKey => $restaurant)
		@php($changes = $restaurant->changes)
		<div class="card">
			<div class="card-content">
				<h5>
					{{$restaurant->name}}

					<a class="expand">
						<i class="la {{ ($indexKey == 0) ? 'la-chevron-up' : 'la-chevron-down'}}"></i>
					</a>
				</h5>
				
				<div class="card content-collapsed" @if($indexKey == 0) style="display: block;"@endif>
					<div class="card-content">
						<h6>Cambios:</h6>
						<table border="0">
							<tr>
								<th>Campo</th>
								<th>Actual</th>
								<th>Nuevo</th>
							</tr>
							@if($changes->name)
							<tr>
								<td>
									Nombre
								</td>
								<td>
									{{$restaurant->name}}
								</td>
								<td>
									{{$changes->name}}
								</td>
							</tr>
							@endif
							@if($changes->phone)
							<tr>
								<td>Teléfono</td>
								<td>
									{{$restaurant->phone}}
								</td>
								<td>
									{{$changes->phone}}
								</td>
							</tr>
							@endif
							@if($changes->address)
							<tr>
								<td>Dirección</td>
								<td>
									{{$restaurant->address}}
								</td>
								<td>
									{{$changes->address}}
								</td>
							</tr>
							@endif
							@if($changes->city_id)
							<tr>
								<td>Ciudad</td>
								<td>
									{{$restaurant->city->name}}, {{$restaurant->city->country}}
								</td>
								<td>
									{{$changes->city->name}}, {{$changes->city->country}}
								</td>
							</tr>
							@endif
							@if($changes->description)
							<tr>
								<td>Descripción</td>
								<td>
									{{$restaurant->description}}
								</td>
								<td>
									{{$changes->description}}
								</td>
							</tr>
							@endif
						</table>
					</div>
					<div class="foot">
						{{ Form::open(['route' => ['admin.approve_changes', $restaurant->id], 'method' => 'POST']) }}
						{{ Form::close() }}

						<button class="button small aprove_js">Aprobar cambios</button>
					</div>
				</div>
			</div>
		</div>
	@empty
	<p class="no-found">No hay restaurantes con cambios pendientes en estos momentos.</p>
	@endforelse
</div>

{{ $restaurants->links() }}

@push('styles')
<link rel="stylesheet" href="/manager/css/vex.css" />
<link rel="stylesheet" href="/manager/css/vex-theme-top.css" />
<style type="text/css">
.card-content h5{
	z-index: 1;
	cursor: pointer;
}
.expand{
	position: absolute;
	right: 15px;
	top: 15px;
	z-index: 0
}
.card-list .card .card-content {
    width: 100%;
}
.card-list .card .card-content > .content-collapsed{
	display: none;
	margin-top: 15px
}
.content-collapsed h6{
	margin:5px 0;
}
table{
	width: calc(100% - 30px);
}
table th, table td {
	max-width: initial;
	width: 200px
}
.foot{
	padding: 5px 15px;
	display: flex;
}
.foot > *:last-child{
	margin-left: auto;
}
</style>
@endpush
@push('scripts')
<script src="/manager/js/vex.combined.min.js"></script>
<script>vex.defaultOptions.className = 'vex-theme-top'</script>
<script type="text/javascript">
	$('.card-content h5').on('click', function (e) {
		e.preventDefault();

		$('.content-collapsed', $(this).parents('.card-content')).toggle();

		$('.expand i', $(this).parents('.card-content')).attr('class', 'la '+($('.expand i', $(this).parents('.card-content')).hasClass('la-chevron-down') ? 'la-chevron-up' : 'la-chevron-down'));
	});

	$('.aprove_js').on('click', function (e) {
		e.preventDefault();

		var $form = $('form', $(this).parents('.foot'));

		vex.dialog.confirm({
			message: "¿Está seguro/a que desea aprobar estos cambios?",
			callback: function (value) {
				if (value)
					$form.submit();
			}
		});
	});
</script>
@endpush
@endsection

resources/views/admin/index.blade.php
@extends('admin.structure')

@section('main_content')
@parent

<div class="card-list"> 
	@forelse ($restaurants as $restaurant)
	@php($photo = $restaurant->photos->first())
	<a href="restaurant" data-id="{{$restaurant->id}}" href-modal load-json="{{route('admin.ajax.rta', $restaurant->id)}}">
	<div class="card">
		<div class="card-thumbnail{{($photo) ? ' image-exists' : ''}}" {!! ($photo) ? 'style="background-image: url('.$photo->getThumbUrl().')"' : '' !!}></div>
		<div class="card-content">
			<h3 class="title">{{ $restaurant->name }}</h3>
			<font class="small ellipsis">{{$restaurant->city->name}}, {{$restaurant->city->country}}</font>
			<div class="icons">
				@if($restaurant->schedulers_days_count > 0) 
					<i class="la la-calendar-o"></i>
				@endif
				@if($restaurant->menu_items_count > 0) 
					<i class="la la-cutlery"></i>
				@endif
				@if($restaurant->photos_count > 0) 
					<i class="la la-camera"></i>
				@endif
			</div>
		</div>
		{{ Form::open(['class' => 'approve_restaurant_form_js', 'route' => ['admin.approve_restaurant', $restaurant->id], 'method' => 'POST']) }}
		{{ Form::close() }}

		{{ Form::open(['class' => 'deny_restaurant_form_js', 'route' => ['admin.deny_restaurant', $restaurant->id], 'method' => 'POST']) }}
			<input type="hidden" value="" name="reason"/>
		{{ Form::close() }}
	</div>
	</a>
	@empty
	<p class="no-found">No hay restaurantes pendientes de aprobación en estos momentos.</p>
	@endforelse

	{{ $restaurants->links() }}
</div>


@push('styles')
<link rel="stylesheet" href="/manager/css/vex.css" />
<link rel="stylesheet" href="/manager/css/vex-theme-top.css" />
<style type="text/css">
	.modal{
		z-index:111;
	}
	.modal .modal-body{
		width:calc(100% - 60px);
		max-width: 900px;
		overflow:auto;
		max-height: calc(100vh - 70px);
	}
	.details {
	    padding: 0;
	    list-style-type: none;
	    margin: 0;
	}
	.details li {
	    display: flex;
	    align-items: center;
	    margin: 5px 0;
	}
	.details li > i {
	    font-size: 21px;
	}
	.details li > div {
	    margin: 0 10px;
	}
	.details li > div h6 {
	    margin: 5px 0;
	}
	.details li > div font {
	    color: #989696;
	    font-weight: 100;
	    font-size: 16px;
	}
	.description{
		margin-top: 20px
	}
	.description p{
		max-height:100px;
		overflow:auto;
		word-break:break-all
	}
	.images{
		margin-top:20px
	}
	.images .card-overflow{
		margin-top: 15px
	}
	.images .card-overflow .card{
		width:205px
	}
	.images .card-overflow .card .card-content {
	    padding: 5px 15px;
	}
	.menu{
		margin-top: 25px
	}
	.menu h2{
	    font-weight: 100 !important;
	    color: #a2a2a2;
	    font-size: 18px;
	}
	.menu hr{
		margin: 0px 0px 15px;
	}
</style>
@endpush
@push('scripts')
<script src="/manager/js/vex.combined.min.js"></script>
<script>vex.defaultOptions.className = 'vex-theme-top'</script>
<script type="text/javascript">
	$.ajaxSetup({
		headers: {
			'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
		}
	});
	
	function loader_bar(show){
		var $bar = $('span.loading-bar');
		if (show)
			$bar.addClass('show');
		else
			$bar.removeClass('show');
	}

	var restaurantModal = function(data){
		console.log(data);
		var template = ` 
				<h2>
					`+data.name+`
					<div class="right">
						<button class="button small grey js_deny" data-id="`+data.id+`">DENEGAR</button>
						<button class="button small js_approbe" data-id="`+data.id+`">APROBAR</button>
					</div>
				</h2>
				<ul class="details">
					<li>
						<i class="la la-minus-square"></i>
						<div>
							<h6>Tipo</h6>
							<font>`+data.type+`</font>
						</div>
					</li>
					<li>
						<i class="la la-map-marker"></i>
						<div>
							<h6>Dirección</h6>
							<font>`+data.address+`</font> <b style="font-size: 14px">`+data.city+`</b>
						</div>
					</li>
					<li>
						<i class="la la-phone"></i>
						<div>
							<h6>Teléfono</h6>
							<font>`+data.phone+`</font>
						</div>
					</li>
					<li>
						<i class="la la-calendar-o"></i>
						<div>
							<h6>Horario</h6>
							<font `+(!data.hasScheduler ? 'style="color:red"' : '')+`>`+((data.hasScheduler) ? 'Si' : 'No')+`</font>
						</div>
					</li>
				</ul>
				
				<div class="description">
					<h5>Descripción</h5>
					<p>`+data.description+`</p>
				</div>
				
				<div class="tags">`;
					for(var i=0; i < data.tags.length; i++){
						template += `<span class="tag">`+data.tags[i]+`</span>`;
					}		
   template += `</div>

				<div class="images">
					<h5>Imágenes</h5>`;
		if(data.photos.length > 0){
	   template += `<div class="card-overflow">`;
						for(var i=0; i < data.photos.length; i++){
							var photo = data.photos[i];

							template += `<div class="card">
											<div class="card-thumbnail image-exists" style="background-image:url(`+photo.thumb+`)"></div>
											<div class="card-content">
												<p>
													`+photo.description+`
												</p>
											</div>
										</div>`;
						};
		template +=	`</div>`;
		}else template += `<p class="no-found">No hay imagenes.</p>`;
		template += `<div class="menu">
						<h2>Menú</h2>
						<hr/>
		`;
		if(data.menu.length > 0){
			for(var i=0; i < data.menu.length; i++){
				var section = data.menu[i];
			template += `<div class="menu-section">
							<div class="menu-section-head">
								<h3>`+section.title+`</h3>
							</div>	
							<div class="menu-items">`;
								for(var j=0; j < section.items.length; j++){
									var item = section.items[j];

									template += `<div class="menu-item">
													<div class="menu-item-head">
														<h5>`+item.name+`</h5>
														<p>`+item.description+`</p>
													</div>
													<div class="menu-item-right">
														<font class="price">`+item.price+`</font>
													</div>
												</div>`;
								}
				template +=	`</div>
						</div>`;
			}
		}else template += `<p class="no-found">No disponible.</p>`;

	template +=	`	</div>
				</div>
		`;

		return template;
	}

	$('body').on('click', '[href-modal]', function(e){
		e.preventDefault();
		
		var data = null;
		if($(this).attr('let-data'))
			data = JSON.parse($(this).attr('let-data'));

		var $modal = $('<div class="modal"></div>');
			$modal.appendTo('body');

		var ref_modal = $(this).attr('href');
				
		function open_modal(d){
			$modal_content = $('<div class="modal-body"></div>');
			$modal_content.html(window[ref_modal+'Modal'](d));

			$modal.append($modal_content);
		}

		function close_modal(){
			$modal.remove();
		}

		$modal.on('click', function(e){
			if($(e.target).hasClass('modal'))
				close_modal();
		});
	
		if($(this).attr('load-json')){
			loader_bar(true);

			$.ajax({
				type: "GET",
				url: $(this).attr('load-json')
			}).done(function(data) {
								
				open_modal(data);

			}).fail(function(jqXHR, textStatus) {
				console.error(textStatus, jqXHR);
				close_modal();
			}).then(function(){
				loader_bar(false);
			});
		}else open_modal(data);
	});

	$('body').on('click', '.js_approbe', function (e) {
		e.preventDefault();

		var id = $(this).data('id');

		vex.dialog.confirm({
			message: "¿Está seguro/a que desea aprobar este restaurante?",
			callback: function (value) {
				if (value){
					var $form = $('.card-list a[data-id="'+id+'"] .approve_restaurant_form_js');
					$form.submit();
				}
			}
		});
	});

	$('body').on('click', '.js_deny', function (e) {
		e.preventDefault();

		var id = $(this).data('id');

		vex.dialog.prompt({
		    message: '¿Está seguro/a que desea denegar la solicitud de aprobación de este restaurante?',
		    placeholder: 'Motivo',
		    callback: function (value) {
		        if(value && value.trim() != ''){
		        	var $form = $('.card-list a[data-id="'+id+'"] .deny_restaurant_form_js');
					$('input[name="reason"]', $form).val(value);
					$form.submit();
		        }
		    }
		})
	});
</script>
@endpush
@endsection

resources/views/admin/login.blade.php
@extends('layouts.admin')

@section('content')
@parent

<div class="card">
	<div class="card-content">
		
        <h2><img src="/assets/img/sm_icon.png"/> Bary admin</h2>
        @if ($errors->has('email') || $errors->has('password'))
        <div class="msg error">
            <strong>Credenciales incorrectas</strong>
        </div>
        @endif

        <form method="POST" action="{{ route('admin.login') }}">
            {{ csrf_field() }}

            <div class="form-field">
                <label>
                    <input id="email" type="email" placeholder="Email" name="email" class="{{ $errors->has('email') || $errors->has('password') ? ' error' : '' }}" value="{{ old('email') }}" required autofocus>
                </label>
            </div>

            <div class="form-field">
                <label>
                    <input id="password" type="password" placeholder="Contraseña" class="{{ $errors->has('email') || $errors->has('password') ? ' error' : '' }}" name="password" required>
                </label>
            </div>

            <div class="foot">
                <button type="submit" class="button">
                    Login
                </button>
            </div>
        </form>
    </div>
</div>
@push('styles')
<link rel="stylesheet" type="text/css" href="/manager/css/auth-card.css"/>
<link rel="stylesheet" type="text/css" href="/manager/css/admin.css"/>
<style type="text/css">
    .card{
        margin-top: 10vh;
    }
</style>
@endpush
@endsection

resources/views/admin/structure.blade.php
@extends('layouts.admin')

@section('content')
@parent
<span class="loading-bar"></span>
<main>
	<section class="background-white">
		<h2>
			<font class="logo">
				<img src="/assets/img/sm_icon.png"/> 
				<span>Bary admin</span>
			</font>
			
			<div class="right">
				{{ Form::open(['route' => 'admin.logout', 'method' => 'POST']) }}
				<button type="submit" class="button small grey">
					<i class="la la-sign-out"></i>
					Cerrar sesión
				</button>
				{{ Form::close() }}
			</div>
		</h2>
		
		<div class="subnav">
			<a href="{{route('admin.index')}}" @if(Route::current()->getName() == 'admin.index') class="active" @endif>Aprobar</a>
			<a href="{{route('admin.changes')}}" @if(Route::current()->getName() == 'admin.changes') class="active" @endif>Revisar cambios</a>
		</div>

		@yield('main_content')
	</section>
</main>
@push('styles')
<link rel="stylesheet" type="text/css" href="/manager/css/admin.css"/>
@endpush
@endsection