routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
	Route::get('', function(){
		return redirect()->route('admin.index');
	});

	Route::get('login', ['as' => 'show_login', 'uses' => 'Admin\AuthController@showLoginForm']);
	Route::post('login', ['as' => 'login', 'uses' => 'Admin\AuthController@login']);

	Route::get('new', ['as' => 'index', 'uses' => 'Admin\ApproveNewRestaurantsController@index']);
	Route::get('_ajax/restaurant_for_approbed/{restaurant_id}', ['as' => 'ajax.rta', 'uses' => 'Admin\ApproveNewRestaurantsController@get_restaurant']);
	Route::post('approve/{id}/new', ['as' => 'approve_restaurant', 'uses' => 'Admin\ApproveNewRestaurantsController@approve']);
	Route::post('deny/{id}/new', ['as' => 'deny_restaurant', 'uses' => 'Admin\ApproveNewRestaurantsController@deny']);

	Route::get('changes', ['as' => 'changes', 'uses' => 'Admin\ApproveRestaurantsChangesController@index']);
	Route::post('approve/{id}/changes', ['as' => 'approve_changes', 'uses' => 'Admin\ApproveRestaurantsChangesController@approve']);

	Route::post('logout', ['as' => 'logout', 'uses' => 'Admin\AuthController@logout']);
});

Route::group(['prefix' => 'c'], function() {
	Route::get('user/verify/{code}', 'VerifyUserController@verify');

	Route::get('user/reset/{token}', 'ResetPwdUserController@showResetForm')->name('c.user.reset');
	Route::post('user/reset', 'ResetPwdUserController@reset')->name('c.user.reset.post');

	Route::get('user/remail/{code}', 'ResetEmailUserController@index')->name('c.user.remail');
});

Route::group(['prefix' => 'manager'], function() {

	// Portada
	Route::get('/', ['as' => 'welcome', 'uses' => 'WelcomePageController@index']);

	// Auth
	Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
	Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
	Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
	Route::group(['prefix' => 'password', 'as' => 'password.'], function() {
		Route::get('reset', ['as' => 'request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
		Route::post('email', ['as' => 'email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
		Route::get('reset/{token}', ['as' => 'reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
		Route::post('reset', ['as' => 'reset', 'uses' => 'Auth\ResetPasswordController@reset']);
	});

	// Asistente de registro (Usuarios y Restaurantes)
	Route::group(['prefix' => 'assistant', 'as' => 'assistant.'], function() {
		Route::get('start', ['as' => 'start', 'uses' => 'Assistant\StartController@showRegistrationForm']);
		Route::post('start', ['as' => 'start.post', 'uses' => 'Assistant\StartController@register']);

		Route::get('create', ['as' => 'create', 'uses' => 'Assistant\CreateController@showRegistrationForm']);
		Route::post('create', ['as' => 'create.post', 'uses' => 'Assistant\CreateController@register']);

		// Peticiones ajax para jquery
		Route::group(['prefix' => '_ajax', 'as' => 'ajax.'], function() {
			Route::get('restaurantTags', ['as' => 'restaurant_tags', 'uses' => 'Assistant\CreateController@getRestaurantTags']);
		});
	});

	/* EMAIL TESTS
	Route::get('mail/view', function ()
	{
		return new App\Mail\UserWelcome();
	});
	*/

	// Administración
	Route::get('/home', 'HomeController@index')->name('home');

	Route::group(['prefix' => 'restaurant', 'as' => 'restaurant.'], function() {

		Route::post('{restaurant_id}/apr', ['as' => 'approve_request', 'uses' => 'RestaurantManage\HomeController@apr']);

		Route::get('{restaurant_id}', ['as' => 'index', 'uses' => 'RestaurantManage\HomeController@index']);

		Route::get('{restaurant_id}/reserves_in_day/{date}', ['as' => 'index.ajax.reserves_data', 'uses' => 'RestaurantManage\HomeController@ajax_reserves_in_day']);
		Route::get('{restaurant_id}/available_dates', ['as' => 'index.ajax.available_dates', 'uses' => 'RestaurantManage\HomeController@ajax_available_days']);
		
		Route::group(['prefix' => '{restaurant_id}/reserves', 'as' => 'reserves.'], function() {
			Route::get('', ['as' => 'index', 'uses' => 'RestaurantManage\ReservesController@index']);

			Route::group(['prefix' => '_ajax', 'as' => 'ajax.'], function() {
				Route::get('events', ['as' => 'get', 'uses' => 'RestaurantManage\ReservesController@ajax_get_events']);
				Route::post('create', ['as' => 'create', 'uses' => 'RestaurantManage\ReservesController@ajax_create_event']);
				Route::post('event/{event_code}/finalize', ['as' => 'finalize', 'uses' => 'RestaurantManage\ReservesController@ajax_finalize_event']);
				Route::post('event/{event_code}/cancel', ['as' => 'cancel', 'uses' => 'RestaurantManage\ReservesController@ajax_cancel_event']);

				Route::get('get_hours_of_date', ['as' => 'av_hours', 'uses' => 'RestaurantManage\ReservesController@ajax_get_hours']);
			});
		});

		Route::group(['prefix' => '{restaurant_id}/menu', 'as' => 'menu.'], function() {
			Route::get('', ['as' => 'index', 'uses' => 'RestaurantManage\MenuController@index']);
			Route::post('', ['as' => 'save', 'uses' => 'RestaurantManage\MenuController@save']);
		});

		Route::resource('{restaurant_id}/photos', 'RestaurantManage\PhotosController');

		Route::post('{restaurant_id}/schedulers/closed_day', ['as' => 'schedulers.closed_day.store', 'uses' => 'RestaurantManage\SchedulersController@closed_day_store']);
		Route::delete('{restaurant_id}/schedulers/closed_day/{cld_date}', ['as' => 'schedulers.closed_day.destroy', 'uses' => 'RestaurantManage\SchedulersController@closed_day_destroy']);
		Route::get('{restaurant_id}/schedulers/{sch_id}/organize', ['as' => 'schedulers.organize', 'uses' => 'RestaurantManage\SchedulersController@organize']);

		// Peticiones ajax para jquery
		Route::group(['prefix' => '{restaurant_id}/schedulers/{sch_id}/_ajax', 'as' => 'schedulers.ajax.'], function() {
			Route::post('sch_day/create', ['as' => 'sch_day.create', 'uses' => 'RestaurantManage\SchedulersController@ajax_create']);
			Route::post('sch_day/update', ['as' => 'sch_day.update', 'uses' => 'RestaurantManage\SchedulersController@ajax_update']);
			Route::post('sch_day/remove', ['as' => 'sch_day.remove', 'uses' => 'RestaurantManage\SchedulersController@ajax_remove']);
		});
		Route::resource('{restaurant_id}/schedulers', 'RestaurantManage\SchedulersController');

		Route::get('{restaurant_id}/statistics', ['as' => 'statistics', 'uses' => 'RestaurantManage\StatisticsController@index']);

		Route::group(['prefix' => '{restaurant_id}/settings', 'as' => 'settings.'], function() {
			Route::get('', ['as' => 'info', 'uses' => 'RestaurantManage\SettingsInfoController@index']);
			Route::put('', ['as' => 'info.save', 'uses' => 'RestaurantManage\SettingsInfoController@save']);

			Route::get('managers', ['as' => 'managers', 'uses' => 'RestaurantManage\SettingsManagersController@index']);
			Route::get('_ajax/users', ['as' => 'managers.ajax.get_users', 'uses' => 'RestaurantManage\SettingsManagersController@ajax_get_users']);
			Route::post('managers', ['as' => 'managers.save', 'uses' => 'RestaurantManage\SettingsManagersController@save']);
		});
		Route::get('c/{code}', ['as' => 'settings.managers.confirmation', 'uses' => 'RestaurantManage\SettingsManagersController@confirmation']);
	});
});

app/Restaurant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Auth;
use Carbon\Carbon;
use Sofa\Eloquence\Eloquence;
use Illuminate\Support\Facades\DB;
use App\RestaurantScheduler;

class Restaurant extends Model
{   
    use Eloquence;

    protected $table = 'restaurant';

    protected $searchableColumns = [
        'name' => 20, 
        'address' => 15,
        'description' => 15,
        'type.name' => 5,
        'tags.name' => 5,
        'menu.title' => 5,
        'menu.items.name' => 5,
        'menu.items.description' => 5,
    ];

	/**
     * Protected attributes that CANNOT be mass assigned.
     *
     * @var array
     */
	protected $guarded = ['id'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
    	'name', 'address', 'phone', 'description', 'city_id', 'restaurant_type_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

    /**
     * Get the restaurant type record associated with the restaurant.
     */
    public function type()
    {	
    	//echo \App\Restaurant::all()->first()->type->name;
    	return $this->hasOne('App\RestaurantType', 'id','restaurant_type_id');
    }

    /**
     * Get the city record associated with the restaurant.
     */
    public function city()
    {	
    	return $this->hasOne('App\City', 'id','city_id');
    }

    /**
     * Get photo records associated with the restaurant.
     */
    public function photos(){
        return $this->hasMany('App\RestaurantPhoto')->orderBy('main', 'DESC')->orderBy('created_at', 'DESC');
    }

    /**
     * Get tags records associated with the restaurant.
     */
    public function tags()
    {	
    	return $this->belongsToMany('App\RestaurantTag');
    }

    public function changes()
    {
        return $this->hasOne('App\RestaurantChanges', 'restaurant_id', 'id');
    }

    public function i()
    {   
        $changes_info = \App\RestaurantChanges::find($this->id);
        $info = new \stdClass;

        $info->name = ($changes_info && $changes_info->name) ? $changes_info->name : $this->name;
        $info->address = ($changes_info && $changes_info->address) ? $changes_info->address : $this->address;
        $info->phone = ($changes_info && $changes_info->phone) ? $changes_info->phone : $this->phone;
        $info->description = ($changes_info && $changes_info->description) ? $changes_info->description : $this->description;
        $info->city_id = ($changes_info && $changes_info->city_id) ? $changes_info->city_id : $this->city_id;

        return $info;
    }

    public function hasPendingChanges()
    {
        return $this->changes()->exists();
    }

    public function isApprobed()
    {
        return $this->approbed == 1;
    }
    
    /**
     * Get scheduler records associated with the restaurant.
     */
    public function schedulers(){
        return $this->hasMany('App\RestaurantScheduler')->orderBy('date_start', 'DESC');
    }

    public function schedulers_days(){
        return $this->hasManyThrough('App\RestaurantSchedulerDay', 'App\RestaurantScheduler', 'restaurant_id', 'scheduler_id', 'id', 'id');
    }

    /**
     * Get managers records associated with the restaurant.
     */
    public function managers(){
        return $this->belongsToMany('App\Manager', 'restaurant_manager')->withPivot('role', 'activation');
    }

    /**
    * Get average price
    */
    public function average_price()
    {   
        $sections = $this->menu->all();
        $avg = 0;
        foreach ($sections as $s) {
            $avg += $s->items()->avg('price');
        }

        if(count($sections) > 0)
            $avg = round($avg/count($sections),2);

        return $avg;
    }

    /**
     * Get menu records associated with the restaurant.
     */
    public function menu()
    {
        return $this->hasMany('App\RestaurantMenuSection')->orderBy('order', 'ASC');
    }

    public function menu_items()
    {
        return $this->hasManyThrough('App\RestaurantMenuItem', 'App\RestaurantMenuSection')->orderBy('order', 'ASC');
    }

    /**
     * Get restaurant rating
     */
    public function rate()
    {
        return ($rate = $this->reviews()->avg('rate')) ? $rate : 0;
    }

    /**
     * Get review records associated with the restaurant.
     */
    public function reviews(){
        return $this->hasMany('App\RestaurantReview')->orderBy('created_at', 'DESC');
    }

    /**
     * Get count of reviews by stars records associated with the restaurant.
     */
    public function rate_count_by_stars(){
        $stars = [];

        for ($i=1; $i <= 5; $i++) { 
            $stars[$i] = $this->reviews()->where('rate', '=', $i)->count();
        }

        return $stars;
    }

    /**
     * Get closed day records associated with the restaurant.
     */
    public function closed_days($start = null, $end = null, $is_equal = false){
        return $this->hasMany('App\RestaurantClosedDay')->where(function($q) use ($start, $end, $is_equal){ // Filtros adicionales
            if($is_equal) { // Si se quiere buscar una fecha en concreto... ($el parametro end se ignorará)
                $q->whereDate('date', '=', $start->toDateString());
            }else{
                if($start !== null) // Si se quiere buscar por fechas iguales o posteriores 
                $q->whereDate('date', '>=', $start->toDateString());
                if($end !== null) // Si se quiere buscar por fechas iguales o anteriores
                $q->whereDate('date', '<=', $end->toDateString());
            }
        })->orderBy('date', 'DESC'); // Mostrar primero los dias mayores
    }

    /**
     * Get reserve records associated with the restaurant.
     */
    public function reserves($date = null){
        return $this->hasMany('App\UserReserve', 'restaurant_id', 'id')->where(function($q) use ($date){ // Filtros adicionales
            if($date !== null) // Si se quiere ver las reservas de un determinado día
            $q->whereRaw("DATE(date) = '$date'");
        })->orderBy('date', 'DESC');
    }

    public function was_client()
    {
        $result = null;

        if(Auth::check())
            $result = $this->reserves()->whereNotNull('date_end')->where(['user_id' => Auth::id(), 'canceled' => 0])->exists();

            return $result;
        }

    /**
     * Get if restaurant is favourite for the user.
     */
    public function is_favourite()
    {
        $favourite = null;

        if(Auth::check())
            $favourite = DB::table('user_restaurant_favourite')->where(['restaurant_id' => $this->id, 'user_id' => Auth::id()])->exists();

            return $favourite;
        }

    /**
     * Get available days for reserve
     */
    public function available_days($hide_full_days = true)
    {  
        // Solo se permite reservar desde el día actual hasta un máximo de 3 meses
        $start_search_date = Carbon::now()->addDay(); // Fecha de inicio para poder reservar
        $finish_search_date = (Carbon::now())->addMonths(3); // Fecha de fin para poder reservar

        $available_days = null; // Valor por defecto de la respuesta (Si no hay horarios para ningúna fecha proxima)
        $schedulers =  RestaurantScheduler::whereFromDate($this->id, array($start_search_date, $finish_search_date));// Obtener horarios que se encuentren entre las fechas permitidas para reservar

        if($schedulers->count() > 0){ // Si hay horarios continuamos
            $available_days = []; // Array para los días que se permiten reservas

            $today = new Carbon(); // Día actual
            if(count($this->available_hours($today)) > 0) // Si hay horas disponibles para reservar hoy
                $available_days[] = $today->toDateString(); // añadir día actual al array de disponibles

            $full_days = []; // Array para los días completos o cerrados
            foreach ($this->closed_days($start_search_date, $finish_search_date)->pluck('date')->toArray() as $date){ // Recorrer dias cerrados que pertenezacn a las fechas posibles de reserva
                $full_days[] = $date->toDateString(); // Añadir días al array
            }
            
            if($hide_full_days){
                foreach (DB::select(DB::raw('SELECT `date` FROM restaurant_full_day WHERE restaurant_id = :id AND `date` >= DATE(NOW()) AND `date` < DATE(DATE_ADD(NOW(), INTERVAL 3 MONTH))'), ['id' => $this->id]) as $fdate){ // Consultar días completos
                    $full_days[] = $fdate->date; // Añadir al array
                }
            }

            $schedulers = $schedulers->orderBy('date_start', 'ASC')->get(); // Obtener horarios de los posibles días de reserva
            foreach ($schedulers as $sch) { // recorrer horarios

                $date_i_start = ($sch->date_start > $start_search_date) ? $sch->date_start : $start_search_date; // Fecha de inicio (El día actual o el día de inicio del horario)
                $date_i_end = (($sch->date_end && $sch->date_end <= $finish_search_date) ? $sch->date_end : $finish_search_date)->addDay(); // (El día de fin de reservas o el dia de fin del horario)
                
                $dwwh = $sch->not_empty_days(); // Obtener días sin horario

                for($date_i = $date_i_start->copy(); $date_i->lte($date_i_end); $date_i->addDay()) { // Recorrer días del horario
                    $day_in_full_day_array = array_search($date_i->toDateString(), $full_days); // Obtener posición de la fecha en el array de 'completos'

                    if($day_in_full_day_array === false){ // Si no se encuentra la fecha en el array de completos
                        if(array_search($date_i->dayOfWeek, $dwwh) !== false) // y tampoco es un dia sin horario
                            $available_days[] = $date_i->toDateString(); // se añade al array de días disponibles

app/RestaurantType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RestaurantType extends Model
{
	protected $table = 'restaurant_type';
	public $timestamps = false;
	
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
    	'id', 'name',
    ];
}

resources/views/restaurant/settings/index.blade.php
@extends('layouts.restaurant')

@section('main_content')
@parent
<div class="subnav">
	<a href="{{route('restaurant.settings.info',$restaurant->id)}}" @if(Route::current()->getName() == 'restaurant.settings.info') class="active" @endif>Información</a>
	<a href="{{route('restaurant.settings.managers',$restaurant->id)}}" @if(Route::current()->getName() == 'restaurant.settings.managers') class="active" @endif>Managers</a>
</div>
@yield('settings_content')
@endsection

resources/views/restaurant/settings/info.blade.php
@extends('restaurant.settings.index')

@section('settings_content')
@parent

{{ Form::open(['class' => 'form max-medium', 'route' => ['restaurant.settings.info.save', $restaurant->id], 'method' => 'PUT']) }}
<div class="columns col2 colm1">
	<div class="form-field">
		<label>Nombre
			<input type="text" class="{{ $errors->has('name') ? 'error' : '' }}" name="name" value="{{ (old('name')) ? old('name') : $restaurant->i()->name }}" required autofocus @if($restaurant->approbed == 2) disabled @endif/>
		</label>

		@if ($errors->has('name'))
		<span class="msg error">
			<strong>{{ $errors->first('name') }}</strong>
		</span>
		@endif
	</div>
	<div class="form-field">
		<label>Ciudad
			<select name="city_id" value="{{ (old('city_id')) ? old('city_id') : $restaurant->i()->city_id }}" @if($restaurant->approbed == 2) disabled @endif>
				<option value="">Select one...</option>

				@foreach($cities as $city)
				<option value="{{$city->id}}">{{$city->name}}, {{$city->country}}</option>
				@endforeach
			</select>
		</label>

		@if ($errors->has('city_id'))
		<span class="msg error">
			<strong>{{ $errors->first('city_id') }}</strong>
		</span>
		@endif
	</div>

	<div class="form-field">
		<label>Dirección
			<textarea name="address" required="required" @if($restaurant->approbed == 2) disabled @endif>{{ (old('address')) ? old('address') : $restaurant->i()->address }}</textarea>
		</label>

		@if ($errors->has('address'))
		<span class="msg error">
			<strong>{{ $errors->first('address') }}</strong>
		</span>
		@endif
	</div>
	<div class="form-field">
		<label>Descripción
			<textarea name="description" required="required" @if($restaurant->approbed == 2) disabled @endif>{{ (old('description')) ? old('description') : $restaurant->i()->description }}</textarea>
		</label>

		@if ($errors->has('description'))
		<span class="msg error">
			<strong>{{ $errors->first('description') }}</strong>
		</span>
		@endif
	</div>
	<div class="form-field">
		<label>Etiquetas (máximo 10) <span class="info">[Separadas por comas]</span>
			<textarea name="tags" class="{{ $errors->has('tags') ? 'error' : '' }}" @if($restaurant->approbed == 2) disabled @endif>{{ (old('tags')) ? old('tags') : $restaurant_tags }}</textarea>
		</label>

		@if ($errors->has('tags'))
		<span class="msg error">
			<strong>{{ $errors->first('tags') }}</strong>
		</span>
		@endif
	</div>
	<div class="form-field">
		<label>Teléfono
			<input type="text" name="phone" required="required" value="{{ (old('phone')) ? old('phone') : $restaurant->i()->phone }}" @if($restaurant->approbed == 2) disabled @endif/>
		</label>

		@if ($errors->has('phone'))
		<span class="msg error">
			<strong>{{ $errors->first('phone') }}</strong>
		</span>
		@endif
	</div>
</div>
@if($restaurant->approbed != 2)
<div class="foot">
	<button type="submit" class="button small success">
		Guardar
	</button>
</div>
@endif
{{ Form::close() }}

@push('styles')
<style type="text/css">
	form{
		margin-top: 20px
	}
</style>
@endpush
@push('scripts')
<script type="text/javascript">
	$("select[name='city_id']").combobox();

	function split( val ) {
		return val.split( /,\s*/ );
	}

	function extractLast( term ) {
		return split( term ).pop();
	}

	$("textarea[name='tags']")
	.on( "keydown", function(event) {
		if(event.keyCode === $.ui.keyCode.TAB && $(this).autocomplete( "instance" ).menu.active ) {
			event.preventDefault();
		}
	})
	.autocomplete({
		source: function(request, response) {
			$.getJSON("{{route('assistant.ajax.restaurant_tags')}}", {
				term: extractLast( request.term )
			}, response );
		},
		search: function() {
			var term = extractLast( this.value );
			if (term.length < 1) {
				return false;
			}
		},
		focus: function() {
			return false;
		},
		select: function(event, ui){
			var terms = split( this.value );
			terms.pop();
			terms.push( ui.item.value );
			terms.push( "" );
			this.value = terms.join( ", " );
			return false;
		}
	});
</script>
@endpush
@endsection

resources/views/restaurant/settings/managers.blade.php
@extends('restaurant.settings.index')

@section('settings_content')
@parent
<label class="search">
	Buscar usuario:
	<input type="text" name="manager"/>
</label>

{{ Form::open(['class' => 'form max-medium', 'route' => ['restaurant.settings.managers.save', $restaurant->id], 'method' => 'POST']) }}
<div class="managers">
	@foreach($restaurant->managers as $manager)
	<div data-userid="{{$manager->id}}">
		<input type="hidden" name="user[]" value='{"id": {{$manager->id}}, "role": "{{$manager->pivot->role}}"}' />
		<div class="info ellipsis">
			<font class="name ellipsis">{{$manager->name}}</font>
			<span class="email ellipsis">{{$manager->email}}</span>
		</div>
		@if(Auth::id() == $manager->id)
		<div class="me" title="Eres tu!">
			<i class="la la-user"></i>
		</div>
		@endif
		@if($manager->pivot->activation)
		<div class="confirmation" title="El usuario deberá aprobarlo vía email">
			<i class="la la-question"></i>
		</div>
		@endif
		<div class="role">
			<div class="select-wrapper">
				<select name="userRole[]" @if(Auth::id() == $manager->id ||$manager->pivot->activation) disabled="disabled" @endif>
					<option value="A" @if($manager->pivot->role == 'A') selected="selected"@endif>Administrador</option>
					<option value="W" @if($manager->pivot->role == 'W') selected="selected"@endif>Camarero</option>
					<option value="S" @if($manager->pivot->role == 'S') selected="selected"@endif>Analista</option>
				</select>
			</div>
		</div>
		<div class="delete">
			@if($manager->pivot->role != 'A' || $num_admins > 1)
			<a href="#" class="delete_manager_js">
				<i class="la la-trash"></i>
			</a>
			@endif
		</div>
	</div>
	@endforeach
</div>
<div class="foot">
	<button class="button small">Guardar</button>
</div>
{{ Form::close() }}
@push('styles')
<style type="text/css">
label.search{
	display: block;
	padding: 10px 0;
}
label.search input{
	display: table;
	margin-top: 5px;
	width: calc(100% - 30px);
	max-width: 320px
}
.managers{
	margin-top: 15px
}
.managers > div{
	display: flex;
	align-items: center;
	position: relative;
	border-bottom: 1px solid #ddd;
	margin-bottom: 5px;
	padding: 10px 0;
}
.managers div.info{
	margin-right: auto;
}
.managers div.info .name{
	display: block;
}
.managers div.info .email{
	margin-top: 5px;
	font-size: 14px;
	color:#777;
	display: block;
}
.managers div.confirmation, .managers div.me{
	margin-left: 10px
}
.managers div.role{
	margin-left: 10px;
	width: 145px
}
.managers div.delete{
	display: block;
	width: 18px;
	margin:10px;
}
</style>
@endpush
@push('scripts')
<script type="text/javascript">
	var managers = JSON.parse('{"users": {!! json_encode($restaurant->managers()->pluck("id"))!!} }');

	$("input[name='manager']").autocomplete({
		minLength: 0,
		source: function(request, response) {
			$.getJSON("{{route('restaurant.settings.managers.ajax.get_users', [$restaurant->id])}}", {
				term: request.term
			}, response );
		},
		select: function( event, ui ) {
			$("input[name='manager']").val('');

			if($('.managers div[data-userid="'+ui.item.id+'"]').length == 0)
				create_element(ui.item);

			return false;
		}
	})
	.autocomplete( "instance" )._renderItem = function(ul, item) {
		return $("<li>")
		.append("<div>"+item.name+"<br> <span style='font-size:12px'>"+item.email+"</span></div>")
		.appendTo(ul);
	};

	function create_element(item) {
		var is_new = (managers.users.indexOf(item.id) == -1);

		var $div = $(
		             '<div data-userid="'+item.id+'">'+
		             '<input type="hidden" name="user[]" value=\'{"id": '+item.id+', "role": "W"}\' />'+
		             '<div class="info ellipsis">'+
		             '<font class="name ellipsis">'+item.name+'</font>'+
		             '<span class="email ellipsis">'+item.email+'</span>'+
		             '</div>'+
		             ((is_new) ? '<div class="confirmation" title="El usuario deberá aprobarlo vía email"><i class="la la-question"></i></div>' : '')+
		             '<div class="role">'+
		             '<div class="select-wrapper">'+
		             '<select name="userRole[]" value="W"><option value="A">Administrador</option><option value="W" selected="selected">Camarero</option><option value="S">Analista</option></select>'+
		             '</div>'+
		             '</div>'+
		             '<div class="delete">'+
		             '<a href="#" class="delete_manager_js">'+
		             '<i class="la la-trash"></i>'+
		             '</a>'+
		             '</div>'+
		             '</div>'
		             );
		$('.managers').append($div);
	}

	$('.managers').on('change', 'select', function(){
		var value = $(this).val();
		var $dataInput = $('input[name="user[]"]', $(this).parents('div[data-userid]'));

		var data = JSON.parse($dataInput.val());
		data.role = value;
		$dataInput.val(JSON.stringify(data));
	});

	$('.managers').on('click', '.delete_manager_js', function (e) {
		e.preventDefault();
		$(this).parents('div[data-userid]').remove();
	});
</script>
@endpush
@endsection