routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
	Route::get('', function(){
		return redirect()->route('admin.index');
	});

	Route::get('login', ['as' => 'show_login', 'uses' => 'Admin\AuthController@showLoginForm']);
	Route::post('login', ['as' => 'login', 'uses' => 'Admin\AuthController@login']);

	Route::get('new', ['as' => 'index', 'uses' => 'Admin\ApproveNewRestaurantsController@index']);
	Route::get('_ajax/restaurant_for_approbed/{restaurant_id}', ['as' => 'ajax.rta', 'uses' => 'Admin\ApproveNewRestaurantsController@get_restaurant']);
	Route::post('approve/{id}/new', ['as' => 'approve_restaurant', 'uses' => 'Admin\ApproveNewRestaurantsController@approve']);
	Route::post('deny/{id}/new', ['as' => 'deny_restaurant', 'uses' => 'Admin\ApproveNewRestaurantsController@deny']);

	Route::get('changes', ['as' => 'changes', 'uses' => 'Admin\ApproveRestaurantsChangesController@index']);
	Route::post('approve/{id}/changes', ['as' => 'approve_changes', 'uses' => 'Admin\ApproveRestaurantsChangesController@approve']);

	Route::post('logout', ['as' => 'logout', 'uses' => 'Admin\AuthController@logout']);
});

Route::group(['prefix' => 'c'], function() {
	Route::get('user/verify/{code}', 'VerifyUserController@verify');

	Route::get('user/reset/{token}', 'ResetPwdUserController@showResetForm')->name('c.user.reset');
	Route::post('user/reset', 'ResetPwdUserController@reset')->name('c.user.reset.post');

	Route::get('user/remail/{code}', 'ResetEmailUserController@index')->name('c.user.remail');
});

Route::group(['prefix' => 'manager'], function() {

	// Portada
	Route::get('/', ['as' => 'welcome', 'uses' => 'WelcomePageController@index']);

	// Auth
	Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
	Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
	Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
	Route::group(['prefix' => 'password', 'as' => 'password.'], function() {
		Route::get('reset', ['as' => 'request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
		Route::post('email', ['as' => 'email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
		Route::get('reset/{token}', ['as' => 'reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
		Route::post('reset', ['as' => 'reset', 'uses' => 'Auth\ResetPasswordController@reset']);
	});

	// Asistente de registro (Usuarios y Restaurantes)
	Route::group(['prefix' => 'assistant', 'as' => 'assistant.'], function() {
		Route::get('start', ['as' => 'start', 'uses' => 'Assistant\StartController@showRegistrationForm']);
		Route::post('start', ['as' => 'start.post', 'uses' => 'Assistant\StartController@register']);

		Route::get('create', ['as' => 'create', 'uses' => 'Assistant\CreateController@showRegistrationForm']);
		Route::post('create', ['as' => 'create.post', 'uses' => 'Assistant\CreateController@register']);

		// Peticiones ajax para jquery
		Route::group(['prefix' => '_ajax', 'as' => 'ajax.'], function() {
			Route::get('restaurantTags', ['as' => 'restaurant_tags', 'uses' => 'Assistant\CreateController@getRestaurantTags']);
		});
	});

	/* EMAIL TESTS
	Route::get('mail/view', function ()
	{
		return new App\Mail\UserWelcome();
	});
	*/

	// Administración
	Route::get('/home', 'HomeController@index')->name('home');

	Route::group(['prefix' => 'restaurant', 'as' => 'restaurant.'], function() {

		Route::post('{restaurant_id}/apr', ['as' => 'approve_request', 'uses' => 'RestaurantManage\HomeController@apr']);

		Route::get('{restaurant_id}', ['as' => 'index', 'uses' => 'RestaurantManage\HomeController@index']);

		Route::get('{restaurant_id}/reserves_in_day/{date}', ['as' => 'index.ajax.reserves_data', 'uses' => 'RestaurantManage\HomeController@ajax_reserves_in_day']);
		Route::get('{restaurant_id}/available_dates', ['as' => 'index.ajax.available_dates', 'uses' => 'RestaurantManage\HomeController@ajax_available_days']);
		
		Route::group(['prefix' => '{restaurant_id}/reserves', 'as' => 'reserves.'], function() {
			Route::get('', ['as' => 'index', 'uses' => 'RestaurantManage\ReservesController@index']);

			Route::group(['prefix' => '_ajax', 'as' => 'ajax.'], function() {
				Route::get('events', ['as' => 'get', 'uses' => 'RestaurantManage\ReservesController@ajax_get_events']);
				Route::post('create', ['as' => 'create', 'uses' => 'RestaurantManage\ReservesController@ajax_create_event']);
				Route::post('event/{event_code}/finalize', ['as' => 'finalize', 'uses' => 'RestaurantManage\ReservesController@ajax_finalize_event']);
				Route::post('event/{event_code}/cancel', ['as' => 'cancel', 'uses' => 'RestaurantManage\ReservesController@ajax_cancel_event']);

				Route::get('get_hours_of_date', ['as' => 'av_hours', 'uses' => 'RestaurantManage\ReservesController@ajax_get_hours']);
			});
		});

		Route::group(['prefix' => '{restaurant_id}/menu', 'as' => 'menu.'], function() {
			Route::get('', ['as' => 'index', 'uses' => 'RestaurantManage\MenuController@index']);
			Route::post('', ['as' => 'save', 'uses' => 'RestaurantManage\MenuController@save']);
		});

		Route::resource('{restaurant_id}/photos', 'RestaurantManage\PhotosController');

		Route::post('{restaurant_id}/schedulers/closed_day', ['as' => 'schedulers.closed_day.store', 'uses' => 'RestaurantManage\SchedulersController@closed_day_store']);
		Route::delete('{restaurant_id}/schedulers/closed_day/{cld_date}', ['as' => 'schedulers.closed_day.destroy', 'uses' => 'RestaurantManage\SchedulersController@closed_day_destroy']);
		Route::get('{restaurant_id}/schedulers/{sch_id}/organize', ['as' => 'schedulers.organize', 'uses' => 'RestaurantManage\SchedulersController@organize']);

		// Peticiones ajax para jquery
		Route::group(['prefix' => '{restaurant_id}/schedulers/{sch_id}/_ajax', 'as' => 'schedulers.ajax.'], function() {
			Route::post('sch_day/create', ['as' => 'sch_day.create', 'uses' => 'RestaurantManage\SchedulersController@ajax_create']);
			Route::post('sch_day/update', ['as' => 'sch_day.update', 'uses' => 'RestaurantManage\SchedulersController@ajax_update']);
			Route::post('sch_day/remove', ['as' => 'sch_day.remove', 'uses' => 'RestaurantManage\SchedulersController@ajax_remove']);
		});
		Route::resource('{restaurant_id}/schedulers', 'RestaurantManage\SchedulersController');

		Route::get('{restaurant_id}/statistics', ['as' => 'statistics', 'uses' => 'RestaurantManage\StatisticsController@index']);

		Route::group(['prefix' => '{restaurant_id}/settings', 'as' => 'settings.'], function() {
			Route::get('', ['as' => 'info', 'uses' => 'RestaurantManage\SettingsInfoController@index']);
			Route::put('', ['as' => 'info.save', 'uses' => 'RestaurantManage\SettingsInfoController@save']);

			Route::get('managers', ['as' => 'managers', 'uses' => 'RestaurantManage\SettingsManagersController@index']);
			Route::get('_ajax/users', ['as' => 'managers.ajax.get_users', 'uses' => 'RestaurantManage\SettingsManagersController@ajax_get_users']);
			Route::post('managers', ['as' => 'managers.save', 'uses' => 'RestaurantManage\SettingsManagersController@save']);
		});
		Route::get('c/{code}', ['as' => 'settings.managers.confirmation', 'uses' => 'RestaurantManage\SettingsManagersController@confirmation']);
	});
});

app/Restaurant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Auth;
use Carbon\Carbon;
use Sofa\Eloquence\Eloquence;
use Illuminate\Support\Facades\DB;
use App\RestaurantScheduler;

class Restaurant extends Model
{   
    use Eloquence;

    protected $table = 'restaurant';

    protected $searchableColumns = [
        'name' => 20, 
        'address' => 15,
        'description' => 15,
        'type.name' => 5,
        'tags.name' => 5,
        'menu.title' => 5,
        'menu.items.name' => 5,
        'menu.items.description' => 5,
    ];

	/**
     * Protected attributes that CANNOT be mass assigned.
     *
     * @var array
     */
	protected $guarded = ['id'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
    	'name', 'address', 'phone', 'description', 'city_id', 'restaurant_type_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

    /**
     * Get the restaurant type record associated with the restaurant.
     */
    public function type()
    {	
    	//echo \App\Restaurant::all()->first()->type->name;
    	return $this->hasOne('App\RestaurantType', 'id','restaurant_type_id');
    }

    /**
     * Get the city record associated with the restaurant.
     */
    public function city()
    {	
    	return $this->hasOne('App\City', 'id','city_id');
    }

    /**
     * Get photo records associated with the restaurant.
     */
    public function photos(){
        return $this->hasMany('App\RestaurantPhoto')->orderBy('main', 'DESC')->orderBy('created_at', 'DESC');
    }

    /**
     * Get tags records associated with the restaurant.
     */
    public function tags()
    {	
    	return $this->belongsToMany('App\RestaurantTag');
    }

    public function changes()
    {
        return $this->hasOne('App\RestaurantChanges', 'restaurant_id', 'id');
    }

    public function i()
    {   
        $changes_info = \App\RestaurantChanges::find($this->id);
        $info = new \stdClass;

        $info->name = ($changes_info && $changes_info->name) ? $changes_info->name : $this->name;
        $info->address = ($changes_info && $changes_info->address) ? $changes_info->address : $this->address;
        $info->phone = ($changes_info && $changes_info->phone) ? $changes_info->phone : $this->phone;
        $info->description = ($changes_info && $changes_info->description) ? $changes_info->description : $this->description;
        $info->city_id = ($changes_info && $changes_info->city_id) ? $changes_info->city_id : $this->city_id;

        return $info;
    }

    public function hasPendingChanges()
    {
        return $this->changes()->exists();
    }

    public function isApprobed()
    {
        return $this->approbed == 1;
    }
    
    /**
     * Get scheduler records associated with the restaurant.
     */
    public function schedulers(){
        return $this->hasMany('App\RestaurantScheduler')->orderBy('date_start', 'DESC');
    }

    public function schedulers_days(){
        return $this->hasManyThrough('App\RestaurantSchedulerDay', 'App\RestaurantScheduler', 'restaurant_id', 'scheduler_id', 'id', 'id');
    }

    /**
     * Get managers records associated with the restaurant.
     */
    public function managers(){
        return $this->belongsToMany('App\Manager', 'restaurant_manager')->withPivot('role', 'activation');
    }

    /**
    * Get average price
    */
    public function average_price()
    {   
        $sections = $this->menu->all();
        $avg = 0;
        foreach ($sections as $s) {
            $avg += $s->items()->avg('price');
        }

        if(count($sections) > 0)
            $avg = round($avg/count($sections),2);

        return $avg;
    }

    /**
     * Get menu records associated with the restaurant.
     */
    public function menu()
    {
        return $this->hasMany('App\RestaurantMenuSection')->orderBy('order', 'ASC');
    }

    public function menu_items()
    {
        return $this->hasManyThrough('App\RestaurantMenuItem', 'App\RestaurantMenuSection')->orderBy('order', 'ASC');
    }

    /**
     * Get restaurant rating
     */
    public function rate()
    {
        return ($rate = $this->reviews()->avg('rate')) ? $rate : 0;
    }

    /**
     * Get review records associated with the restaurant.
     */
    public function reviews(){
        return $this->hasMany('App\RestaurantReview')->orderBy('created_at', 'DESC');
    }

    /**
     * Get count of reviews by stars records associated with the restaurant.
     */
    public function rate_count_by_stars(){
        $stars = [];

        for ($i=1; $i <= 5; $i++) { 
            $stars[$i] = $this->reviews()->where('rate', '=', $i)->count();
        }

        return $stars;
    }

    /**
     * Get closed day records associated with the restaurant.
     */
    public function closed_days($start = null, $end = null, $is_equal = false){
        return $this->hasMany('App\RestaurantClosedDay')->where(function($q) use ($start, $end, $is_equal){ // Filtros adicionales
            if($is_equal) { // Si se quiere buscar una fecha en concreto... ($el parametro end se ignorará)
                $q->whereDate('date', '=', $start->toDateString());
            }else{
                if($start !== null) // Si se quiere buscar por fechas iguales o posteriores 
                $q->whereDate('date', '>=', $start->toDateString());
                if($end !== null) // Si se quiere buscar por fechas iguales o anteriores
                $q->whereDate('date', '<=', $end->toDateString());
            }
        })->orderBy('date', 'DESC'); // Mostrar primero los dias mayores
    }

    /**
     * Get reserve records associated with the restaurant.
     */
    public function reserves($date = null){
        return $this->hasMany('App\UserReserve', 'restaurant_id', 'id')->where(function($q) use ($date){ // Filtros adicionales
            if($date !== null) // Si se quiere ver las reservas de un determinado día
            $q->whereRaw("DATE(date) = '$date'");
        })->orderBy('date', 'DESC');
    }

    public function was_client()
    {
        $result = null;

        if(Auth::check())
            $result = $this->reserves()->whereNotNull('date_end')->where(['user_id' => Auth::id(), 'canceled' => 0])->exists();

            return $result;
        }

    /**
     * Get if restaurant is favourite for the user.
     */
    public function is_favourite()
    {
        $favourite = null;

        if(Auth::check())
            $favourite = DB::table('user_restaurant_favourite')->where(['restaurant_id' => $this->id, 'user_id' => Auth::id()])->exists();

            return $favourite;
        }

    /**
     * Get available days for reserve
     */
    public function available_days($hide_full_days = true)
    {  
        // Solo se permite reservar desde el día actual hasta un máximo de 3 meses
        $start_search_date = Carbon::now()->addDay(); // Fecha de inicio para poder reservar
        $finish_search_date = (Carbon::now())->addMonths(3); // Fecha de fin para poder reservar

        $available_days = null; // Valor por defecto de la respuesta (Si no hay horarios para ningúna fecha proxima)
        $schedulers =  RestaurantScheduler::whereFromDate($this->id, array($start_search_date, $finish_search_date));// Obtener horarios que se encuentren entre las fechas permitidas para reservar

        if($schedulers->count() > 0){ // Si hay horarios continuamos
            $available_days = []; // Array para los días que se permiten reservas

            $today = new Carbon(); // Día actual
            if(count($this->available_hours($today)) > 0) // Si hay horas disponibles para reservar hoy
                $available_days[] = $today->toDateString(); // añadir día actual al array de disponibles

            $full_days = []; // Array para los días completos o cerrados
            foreach ($this->closed_days($start_search_date, $finish_search_date)->pluck('date')->toArray() as $date){ // Recorrer dias cerrados que pertenezacn a las fechas posibles de reserva
                $full_days[] = $date->toDateString(); // Añadir días al array
            }
            
            if($hide_full_days){
                foreach (DB::select(DB::raw('SELECT `date` FROM restaurant_full_day WHERE restaurant_id = :id AND `date` >= DATE(NOW()) AND `date` < DATE(DATE_ADD(NOW(), INTERVAL 3 MONTH))'), ['id' => $this->id]) as $fdate){ // Consultar días completos
                    $full_days[] = $fdate->date; // Añadir al array
                }
            }

            $schedulers = $schedulers->orderBy('date_start', 'ASC')->get(); // Obtener horarios de los posibles días de reserva
            foreach ($schedulers as $sch) { // recorrer horarios

                $date_i_start = ($sch->date_start > $start_search_date) ? $sch->date_start : $start_search_date; // Fecha de inicio (El día actual o el día de inicio del horario)
                $date_i_end = (($sch->date_end && $sch->date_end <= $finish_search_date) ? $sch->date_end : $finish_search_date)->addDay(); // (El día de fin de reservas o el dia de fin del horario)
                
                $dwwh = $sch->not_empty_days(); // Obtener días sin horario

                for($date_i = $date_i_start->copy(); $date_i->lte($date_i_end); $date_i->addDay()) { // Recorrer días del horario
                    $day_in_full_day_array = array_search($date_i->toDateString(), $full_days); // Obtener posición de la fecha en el array de 'completos'

                    if($day_in_full_day_array === false){ // Si no se encuentra la fecha en el array de completos
                        if(array_search($date_i->dayOfWeek, $dwwh) !== false) // y tampoco es un dia sin horario
                            $available_days[] = $date_i->toDateString(); // se añade al array de días disponibles

app/RestaurantType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RestaurantType extends Model
{
	protected $table = 'restaurant_type';
	public $timestamps = false;
	
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
    	'id', 'name',
    ];
}

resources/views/restaurant/index.blade.php
@extends('layouts.restaurant')

@section('main_content')
@parent
<div class="charts">
	<div class="reserve_days">
		<h4>Reservas esta semana</h4>
		<div>
			<canvas data-value="{!!$week_reserves!!}"></canvas>
		</div>
	</div>
	<div class="reserve_hours">
		<h4>Reservas hoy</h4>
		<canvas data-value='{!!$today_reserves!!}'></canvas>
	</div>
</div>
<hr style="margin: 25px 0px 0px;border-color: #eee;">
<h4 style="margin: 25px 10px 5px;">Reservas por dia</h4>
<div class="full_days" style="display: none;">
	<div class="ll-skin-melon"><div class="calendar"></div></div>
	<div class="reserves_data">
		<p>Loading...</p>
	</div>
</div>
<p class="no-found full_days_none_js" style="display: none">
	No hay días de apertura próximos.
</p>
@push('styles')
<link rel="stylesheet" type="text/css" href="/manager/css/melon.datepicker.css"/>
<link rel="stylesheet" type="text/css" href="/manager/css/home-manage.css"/>
@endpush
@push('scripts')
<script type="text/javascript" src="/manager/js/moment-with-locales.js"></script>
<script type="text/javascript" src="/manager/js/chart.bundle.min.js"></script>
<script type="text/javascript">
	var GET_AVAILABLE_DATES = "{!! route('restaurant.index.ajax.available_dates', [$restaurant->id]) !!}";
	var GET_RESERVES_DATA = "{!! route('restaurant.index.ajax.reserves_data', [$restaurant->id, '']) !!}";
</script>
<script type="text/javascript" src="/manager/js/home-manage.js"></script>
@endpush
@endsection

resources/views/restaurant/menu.blade.php
@extends('layouts.restaurant')

@section('main_content')
@parent
@php ($role = Auth::guard()->user()->hasRoleAt($restaurant->id))
{{ Form::open(['route' => ['restaurant.menu.save', $restaurant->id], 'method' => 'POST']) }}
@if($role == 'A')
<h4><!--Menú: -->
	<div class="right">
		<a class="button small grey" type="button" id="create_section_js" alt="Arrastre o haga click para crear" title="Arrastre o haga click para crear"><i class="la la-plus" alt=""></i> Sección</a>
		<a class="button small grey" type="button" id="create_item_js" alt="Arrastre o haga click para crear" title="Arrastre o haga click para crear"><i class="la la-plus" alt=""></i> Item</a>
		<button class="button small" type="submit" id="save">Guardar</button>
	</div>
</h4>
@endif
<div class="menu @if($role == 'A') editable @endif">@foreach($restaurant->menu as $menu_section)
	<div class="menu-section" data-id="{{$menu_section->id}}">
		<input type="hidden" name="menu_section[]" value='{"id": "{{$menu_section->id}}"}'/>
		@if($role == 'A')
		<div class="toolbar">
			<a href="#" class="edit_si_js" data-tooltip-content='#edit_section' alt="Editar sección"><i class="la la-pencil" alt=""></i></a>
			<a href="#" class="delete_si_js" alt="Borrar sección"><i class="la la-trash" alt=""></i></a>
		</div>
		@endif
		<div class="menu-section-head">
			<h3>
				@if($menu_section->icon)
				<i class="eat eat-{{$menu_section->icon}}"></i>
				@endif
				<font>{{$menu_section->title}}</font>
			</h3>
		</div>
		<div class="menu-items">@foreach($menu_section->items as $menu_item)
			<div class="menu-item" data-id="{{$menu_item->id}}">
				<input type="hidden" name="menu_item[]" value='{"id": "{{$menu_item->id}}"}'/>
				@if($role == 'A')
				<div class="toolbar">
					<a href="#" class="edit_si_js" data-tooltip-content='#edit_item' alt="Editar item"><i class="la la-pencil" alt=""></i></a>
					<a href="#" class="delete_si_js" alt="Eliminar item"><i class="la la-trash" alt=""></i></a>
				</div>
				@endif
				<div class="menu-item-head">
					<h5>{{$menu_item->name}}</h5>
					<p>{{$menu_item->description}}</p>
				</div>
				<div class="menu-item-right">
					<font class="price">{{$menu_item->price}}€</font>
				</div>
			</div>
		@endforeach</div>
	</div>
@endforeach</div>
{{ Form::close() }}
<div class="tooltip_templates">
	<div id="edit_section">
		<div class="option">
			<label>Icono:
				<div class="icons">
					@foreach(\App\RestaurantMenuSection::$ICONS as $icon)
					<a href="#"><i class="eat eat-{{$icon}}"></i></a>
					@endforeach
				</div>
			</label>
		</div>
		<div class="option">
			<label>
				Titulo:
				<input type="text" name="title" autofocus="" />
			</label>
		</div>
	</div>
	<div id="edit_item">
		<div class="option">
			<label>
				Nombre:
				<input type="text" name="name" autofocus/>
			</label>
		</div>
		<div class="option">
			<label>
				Descripción:
				<input type="text" name="description"/>
			</label>
		</div>
		<div class="option">
			<label>
				Precio:
				<input type="number" name="price" step="0.01" min="0.05"/>
			</label>
		</div>
	</div>
</div>
@push('styles')
<link rel="stylesheet" type="text/css" href="/assets/css/eat-icons.css"/>
<link rel="stylesheet" type="text/css" href="/manager/css/menu-creator.css"/>
@if($role == 'A')
<link rel="stylesheet" type="text/css" href="/manager/css/tooltipster.bundle.min.css"/>
@endif
@endpush
@push('scripts')
@if($role == 'A')
<script type="text/javascript" src="/manager/js/tooltipster.bundle.min.js"></script>
<script type="text/javascript" src="/manager/js/menu-creator.js"></script>
@endif
@endpush
@endsection

resources/views/restaurant/statistics.blade.php
@extends('layouts.restaurant')

@section('main_content')
@parent
<div class="charts">
	<div class="reserve_months">
		<h4>Reservas por mes</h4>
		<canvas></canvas>
	</div>
	
	<div class="scheduler-stats">
		<div class="week_average_time">
			<h4>Tiempo medio de estancia en min. (horario actual) [{{$total_average_time}} min.]</h4>
			<canvas data-value="{!! $week_average_time !!}"></canvas>
		</div>

		<div class="reserve_types">
			<h4>Cantidad de reservas (horario actual)</h4>
			<div>
				<canvas data-value="{!! $reserve_types !!}"></canvas>
			</div>
		</div>
	</div>
</div>
@push('styles')
<link rel="stylesheet" type="text/css" href="/manager/css/statistics.css"/>
@endpush
@push('scripts')
<script type="text/javascript" src="/manager/js/moment-with-locales.js"></script>
<script type="text/javascript" src="/manager/js/chart.bundle.min.js"></script>
<script type="text/javascript">
	var MONTH_RESERVES = {!! $month_reserves !!};
</script>
<script type="text/javascript" src="/manager/js/statistics.js"></script>
@endpush
@endsection