routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
	Route::get('', function(){
		return redirect()->route('admin.index');
	});

	Route::get('login', ['as' => 'show_login', 'uses' => 'Admin\AuthController@showLoginForm']);
	Route::post('login', ['as' => 'login', 'uses' => 'Admin\AuthController@login']);

	Route::get('new', ['as' => 'index', 'uses' => 'Admin\ApproveNewRestaurantsController@index']);
	Route::get('_ajax/restaurant_for_approbed/{restaurant_id}', ['as' => 'ajax.rta', 'uses' => 'Admin\ApproveNewRestaurantsController@get_restaurant']);
	Route::post('approve/{id}/new', ['as' => 'approve_restaurant', 'uses' => 'Admin\ApproveNewRestaurantsController@approve']);
	Route::post('deny/{id}/new', ['as' => 'deny_restaurant', 'uses' => 'Admin\ApproveNewRestaurantsController@deny']);

	Route::get('changes', ['as' => 'changes', 'uses' => 'Admin\ApproveRestaurantsChangesController@index']);
	Route::post('approve/{id}/changes', ['as' => 'approve_changes', 'uses' => 'Admin\ApproveRestaurantsChangesController@approve']);

	Route::post('logout', ['as' => 'logout', 'uses' => 'Admin\AuthController@logout']);
});

Route::group(['prefix' => 'c'], function() {
	Route::get('user/verify/{code}', 'VerifyUserController@verify');

	Route::get('user/reset/{token}', 'ResetPwdUserController@showResetForm')->name('c.user.reset');
	Route::post('user/reset', 'ResetPwdUserController@reset')->name('c.user.reset.post');

	Route::get('user/remail/{code}', 'ResetEmailUserController@index')->name('c.user.remail');
});

Route::group(['prefix' => 'manager'], function() {

	// Portada
	Route::get('/', ['as' => 'welcome', 'uses' => 'WelcomePageController@index']);

	// Auth
	Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
	Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
	Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
	Route::group(['prefix' => 'password', 'as' => 'password.'], function() {
		Route::get('reset', ['as' => 'request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
		Route::post('email', ['as' => 'email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
		Route::get('reset/{token}', ['as' => 'reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
		Route::post('reset', ['as' => 'reset', 'uses' => 'Auth\ResetPasswordController@reset']);
	});

	// Asistente de registro (Usuarios y Restaurantes)
	Route::group(['prefix' => 'assistant', 'as' => 'assistant.'], function() {
		Route::get('start', ['as' => 'start', 'uses' => 'Assistant\StartController@showRegistrationForm']);
		Route::post('start', ['as' => 'start.post', 'uses' => 'Assistant\StartController@register']);

		Route::get('create', ['as' => 'create', 'uses' => 'Assistant\CreateController@showRegistrationForm']);
		Route::post('create', ['as' => 'create.post', 'uses' => 'Assistant\CreateController@register']);

		// Peticiones ajax para jquery
		Route::group(['prefix' => '_ajax', 'as' => 'ajax.'], function() {
			Route::get('restaurantTags', ['as' => 'restaurant_tags', 'uses' => 'Assistant\CreateController@getRestaurantTags']);
		});
	});

	/* EMAIL TESTS
	Route::get('mail/view', function ()
	{
		return new App\Mail\UserWelcome();
	});
	*/

	// Administración
	Route::get('/home', 'HomeController@index')->name('home');

	Route::group(['prefix' => 'restaurant', 'as' => 'restaurant.'], function() {

		Route::post('{restaurant_id}/apr', ['as' => 'approve_request', 'uses' => 'RestaurantManage\HomeController@apr']);

		Route::get('{restaurant_id}', ['as' => 'index', 'uses' => 'RestaurantManage\HomeController@index']);

		Route::get('{restaurant_id}/reserves_in_day/{date}', ['as' => 'index.ajax.reserves_data', 'uses' => 'RestaurantManage\HomeController@ajax_reserves_in_day']);
		Route::get('{restaurant_id}/available_dates', ['as' => 'index.ajax.available_dates', 'uses' => 'RestaurantManage\HomeController@ajax_available_days']);
		
		Route::group(['prefix' => '{restaurant_id}/reserves', 'as' => 'reserves.'], function() {
			Route::get('', ['as' => 'index', 'uses' => 'RestaurantManage\ReservesController@index']);

			Route::group(['prefix' => '_ajax', 'as' => 'ajax.'], function() {
				Route::get('events', ['as' => 'get', 'uses' => 'RestaurantManage\ReservesController@ajax_get_events']);
				Route::post('create', ['as' => 'create', 'uses' => 'RestaurantManage\ReservesController@ajax_create_event']);
				Route::post('event/{event_code}/finalize', ['as' => 'finalize', 'uses' => 'RestaurantManage\ReservesController@ajax_finalize_event']);
				Route::post('event/{event_code}/cancel', ['as' => 'cancel', 'uses' => 'RestaurantManage\ReservesController@ajax_cancel_event']);

				Route::get('get_hours_of_date', ['as' => 'av_hours', 'uses' => 'RestaurantManage\ReservesController@ajax_get_hours']);
			});
		});

		Route::group(['prefix' => '{restaurant_id}/menu', 'as' => 'menu.'], function() {
			Route::get('', ['as' => 'index', 'uses' => 'RestaurantManage\MenuController@index']);
			Route::post('', ['as' => 'save', 'uses' => 'RestaurantManage\MenuController@save']);
		});

		Route::resource('{restaurant_id}/photos', 'RestaurantManage\PhotosController');

		Route::post('{restaurant_id}/schedulers/closed_day', ['as' => 'schedulers.closed_day.store', 'uses' => 'RestaurantManage\SchedulersController@closed_day_store']);
		Route::delete('{restaurant_id}/schedulers/closed_day/{cld_date}', ['as' => 'schedulers.closed_day.destroy', 'uses' => 'RestaurantManage\SchedulersController@closed_day_destroy']);
		Route::get('{restaurant_id}/schedulers/{sch_id}/organize', ['as' => 'schedulers.organize', 'uses' => 'RestaurantManage\SchedulersController@organize']);

		// Peticiones ajax para jquery
		Route::group(['prefix' => '{restaurant_id}/schedulers/{sch_id}/_ajax', 'as' => 'schedulers.ajax.'], function() {
			Route::post('sch_day/create', ['as' => 'sch_day.create', 'uses' => 'RestaurantManage\SchedulersController@ajax_create']);
			Route::post('sch_day/update', ['as' => 'sch_day.update', 'uses' => 'RestaurantManage\SchedulersController@ajax_update']);
			Route::post('sch_day/remove', ['as' => 'sch_day.remove', 'uses' => 'RestaurantManage\SchedulersController@ajax_remove']);
		});
		Route::resource('{restaurant_id}/schedulers', 'RestaurantManage\SchedulersController');

		Route::get('{restaurant_id}/statistics', ['as' => 'statistics', 'uses' => 'RestaurantManage\StatisticsController@index']);

		Route::group(['prefix' => '{restaurant_id}/settings', 'as' => 'settings.'], function() {
			Route::get('', ['as' => 'info', 'uses' => 'RestaurantManage\SettingsInfoController@index']);
			Route::put('', ['as' => 'info.save', 'uses' => 'RestaurantManage\SettingsInfoController@save']);

			Route::get('managers', ['as' => 'managers', 'uses' => 'RestaurantManage\SettingsManagersController@index']);
			Route::get('_ajax/users', ['as' => 'managers.ajax.get_users', 'uses' => 'RestaurantManage\SettingsManagersController@ajax_get_users']);
			Route::post('managers', ['as' => 'managers.save', 'uses' => 'RestaurantManage\SettingsManagersController@save']);
		});
		Route::get('c/{code}', ['as' => 'settings.managers.confirmation', 'uses' => 'RestaurantManage\SettingsManagersController@confirmation']);
	});
});

app/Http/Controllers/RestaurantManage/SchedulersController.php
<?php

namespace App\Http\Controllers\RestaurantManage;

use App\Http\Controllers\Controller;
use App\Restaurant;
use App\RestaurantScheduler;
use App\RestaurantSchedulerDay;

use App\RestaurantClosedDay;

use Carbon\Carbon;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;

use App\Validations\SchedulerDateNotIn;

class SchedulersController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
    	$this->middleware(['auth', 'role'], ['only' => ['index', 'organize']]);
        $this->middleware(['auth', 'role:A'], ['except' => ['index', 'organize']]);
    }

    public function show($restaurant_id, $sch_id){
        return view('errors.404');
    }

    /**
     * Show the restaurant schedules.
     *
     * @return HTML
     */
    public function index($restaurant_id)
    {	
    	$restaurant = Restaurant::with('schedulers')->find($restaurant_id);

        return view('restaurant.schedulers.index', ['restaurant' => $restaurant]);
    }

    public function ajax_create($restaurant_id, $sch_id, Request $request){
    	$data = $request->only(['sch_day_hour_start','sch_day_hour_end', 'sch_day_week_day', 'sch_day_code']);
    	$data['sch_id'] = $sch_id;

    	$validator = Validator::make($data, [
    		'sch_id' => 'required|integer|exists:restaurant_scheduler,id',
    		'sch_day_hour_start' => 'required|string',
    		'sch_day_hour_end' => 'required|string',
    		'sch_day_week_day' => 'required|in:L,M,X,J,V,S,D',
    		'sch_day_code' => 'required|string|unique:restaurant_scheduler_day,code'
    	])->validate();

        $result = RestaurantSchedulerDay::create([
          'code' => $data['sch_day_code'],
          'scheduler_id' => $data['sch_id'],
          'hour_start' => $data['sch_day_hour_start'],
          'hour_end' => $data['sch_day_hour_end'],
          'week_day' => array_search($data['sch_day_week_day'], RestaurantSchedulerDay::$WEEK_NAMES)
      ]);

        return ['status' => $result];
    }

    public function ajax_update($restaurant_id, $sch_id, Request $request){
    	$data = $request->only(['sch_day_code', 'sch_day_hour_start','sch_day_hour_end', 'sch_day_week_day']);

    	$validator = Validator::make($data, [
    		'sch_day_code' => 'required|string|exists:restaurant_scheduler_day,code',
    		'sch_day_hour_start' => 'required|string',
    		'sch_day_hour_end' => 'required|string',
    		'sch_day_week_day' => 'required|in:L,M,X,J,V,S,D'
    	])->validate();

    	$result = false;

    	$day = RestaurantSchedulerDay::where(['code' => $data['sch_day_code']]);
    	if($day !== null)
    		$result = $day->update(['week_day' => array_search($data['sch_day_week_day'], RestaurantSchedulerDay::$WEEK_NAMES), 'hour_start' => $data['sch_day_hour_start'], 'hour_end' => $data['sch_day_hour_end']]);

    	return ['status' => $result];
    }

    public function ajax_remove($restaurant_id, $sch_id, Request $request){
    	$data = $request->only(['sch_day_code']);

    	$validator = Validator::make($data, [
    		'sch_day_code' => 'required|string|exists:restaurant_scheduler_day,code'
    	])->validate();

    	$result = RestaurantSchedulerDay::where(['code' => $data['sch_day_code']])->delete();

    	return ['status' => $result];
    }

    /**
     * Edit a restaurant schedule.
     *
     * @return HTML
     */
    public function organize($restaurant_id, $sch_id)
    {	
    	$restaurant = Restaurant::find($restaurant_id);
    	$scheduler = RestaurantScheduler::with('days')->find($sch_id);

    	$scheduler_days = [];

        $now = Carbon::today('Europe/Brussels')->toDateString();

        foreach ($scheduler->days as $day) {

            $hour_start_split = preg_split('/:/', $day->hour_start);
            $hour_end_split = preg_split('/:/', $day->hour_end);

            $scheduler_days[] = [
             'id' => $day->code,
             'resourceId' => RestaurantSchedulerDay::$WEEK_NAMES[$day->week_day],
             'start' => $now.'T'.$hour_start_split[0].':'.$hour_start_split[1],
             'end' => $now.'T'.$hour_end_split[0].':'.$hour_end_split[1],
         ];
     }

     return view('restaurant.schedulers.organize', ['restaurant' => $restaurant, 'scheduler' => $scheduler, 'scheduler_days' => $scheduler_days]);
 }

    /**
    *  Validator for Create or edit a scheduler
    *  @return Validator
    */
    private function validator($restaurant_id, $data, $scheduler_id=null){
        return Validator::make($data, [
            'date_start' => ['required', 'date', new SchedulerDateNotIn($restaurant_id, $scheduler_id)], // No se encuentre en otro calendario del mismo restaurante
            'date_end' => ['date', 'after:'.date($data['date_start']), new SchedulerDateNotIn($restaurant_id, $scheduler_id)], // Que sea mayor a la fecha de inicio y que no se encuentre en otro calendario del mismo restaurante
            'description' => 'required|string',
            'capacity' => 'required|integer|min:25|max:200',
            'average_time' => ['required', 'integer', 'min:30', 'max:180', function($attribute, $value, $fail){
                if($value%5 !== 0)
                    fail('Valor fuera del rango');
            }]
        ]);
    }

    /**
    * Create a restaurant schedule.
    * 
    * @return HTML
    */
    public function create($restaurant_id)
    {
    	$restaurant = Restaurant::find($restaurant_id);

    	return view('restaurant.schedulers.create', ['restaurant' => $restaurant]);
    }

    /**
    * Edit a restaurant schedule.
    * 
    * @return HTML
    */
    public function edit($restaurant_id, $sch_id)
    {
        $restaurant = Restaurant::find($restaurant_id);
        $scheduler = RestaurantScheduler::find($sch_id);

        return view('restaurant.schedulers.create', ['restaurant' => $restaurant, 'scheduler' => $scheduler]);
    }

    private function pre_save($restaurant_id, $data, $scheduler_id=null)
    {   
        /*
        * pass dates from Spanish format to basic
        */
        if(isset($data['date_start']))
            $data['date_start'] = (Carbon::createFromFormat('d/m/Y', $data['date_start']))->toDateString();
        

        if(isset($data['date_end']) && !empty(trim($data['date_end'])))
            $data['date_end'] = (Carbon::createFromFormat('d/m/Y', $data['date_end']))->toDateString();

        /*
        * validate fields
        */
        $this->validator($restaurant_id, $data, $scheduler_id)->validate();

        $unclosed_restaurant_scheduler = RestaurantScheduler::where([['restaurant_id', '=', $restaurant_id], ['date_start', '<=', $data['date_start']], ['id', '!=', $scheduler_id]])->whereNull('date_end')->first(); // Obtener el calendario que pertenezca a las fechas seleccionadas cuya fecha de fin no esté establecida

        if($unclosed_restaurant_scheduler != null){ // si hay alguno
            $date_end_unclosed_rs = (new Carbon($data['date_start']))->addDay()->toDateString(); // restar 1 dia a la fecha de inicio

            if($date_end_unclosed_rs > $unclosed_restaurant_scheduler->date_start){ // si la fecha restada no es menor o igual a la fecha de inicio de este calendario
                $unclosed_restaurant_scheduler->update([
                    'date_end' => $date_end_unclosed_rs // Poner fecha de fin
                ]);
            }else return 'Error';
        }

        if(empty(trim($data['date_end']))){
            $after_restaurant_scheduler = RestaurantScheduler::where([['restaurant_id', '=', $restaurant_id], ['date_start', '>', $data['date_start']], ['id', '!=', $scheduler_id]])->first();
            
            if($after_restaurant_scheduler != null){
                $date_end_after_rs = (new Carbon($after_restaurant_scheduler->date_start))->subDay()->toDateString(); // restar 1 dia a la fecha de inicio

                if($date_end_after_rs > $data['date_start'])
                    $data['date_end'] = $date_end_after_rs;
                else return 'Error';
            }
        }

        return $data;
    }

    /**
    * Create (POST) a restaurant schedule.
    * 
    * @return HTML
    */
    public function store($restaurant_id, Request $request)
    {
        $data = $this->pre_save($restaurant_id, $request->only(['date_start', 'date_end','description', 'capacity', 'average_time']));

    	/*
    	* Crear calendario
    	*/
    	$new_element_properties = [
    		'restaurant_id' => $restaurant_id,
    		'date_start' => $data['date_start'],
    		'description' => $data['description'],
            'capacity' => $data['capacity'],
            'average_time' => $data['average_time']
        ];

        if(!empty(trim($data['date_end'])))
          $new_element_properties['date_end'] = $data['date_end'];

      $new_save = RestaurantScheduler::create($new_element_properties);

      if($new_save)
    		return redirect(route('restaurant.schedulers.organize', [$restaurant_id, $new_save->id])); // Redirigir a la página de organización
    }

    /**
    * Update (PUT) a restaurant schedule.
    * 
    * @return HTML
    */
    public function update($restaurant_id, $sch_id, Request $request)
    {
        $data = $this->pre_save($restaurant_id, $request->only(['date_start', 'date_end','description', 'capacity', 'average_time']), $sch_id);

        /*
        * Actualizar calendario
        */
        $properties = [
            'date_start' => $data['date_start'],
            'description' => $data['description'],
            'capacity' => $data['capacity'],
            'average_time' => $data['average_time']
        ];

        if(!empty(trim($data['date_end'])))
            $properties['date_end'] = $data['date_end'];

        $update = RestaurantScheduler::find($sch_id)->update($properties);
        if($update)
            return redirect(route('restaurant.schedulers.index', $restaurant_id));
    }

    public function destroy($restaurant_id, $sch_id)
    {

resources/views/restaurant/schedulers/create.blade.php
@extends('layouts.restaurant')

@section('main_content')
<h4>{{ (isset($scheduler)) ? 'Editar horario "'.$scheduler->description.'"' : 'Crear nuevo horario' }}</h4>

@php
$route = ['restaurant.schedulers.store', $restaurant->id];
$method = 'POST';

if(isset($scheduler)){
$method = 'PUT';
$route[0] = 'restaurant.schedulers.update';
$route[] = $scheduler->id;
}
@endphp

{{ Form::open(['class' => 'form max-medium', 'route' => $route, 'method' => $method]) }}
<p class="info">Recuerde que las fechas no pueden pertenecer a otro horario creado.</p>

<div class="columns col2 colm1">
	<div class="form-field">
		<label>Fecha inicio:
			<input type="text" class="{{ $errors->has('date_start') ? 'error' : '' }}" name="date_start" placeholder="dd/mm/yyyy" value="{{ (old('date_start')) ? old('date_start') : ((isset($scheduler)) ? (new Carbon\Carbon($scheduler->date_start))->format('d/m/Y') : '') }}" required/>
		</label>

		@if ($errors->has('date_start'))
		<span class="msg error">
			<strong>{{ $errors->first('date_start') }}</strong>
		</span>
		@endif
	</div>
	<div class="form-field">
		<label>Fecha fin:
			<input type="text" class="{{ $errors->has('date_end') ? 'error' : '' }}" name="date_end" placeholder="dd/mm/yyyy" value="{{ (old('date_end')) ? old('date_end') : ((isset($scheduler) && $scheduler->date_end) ? (new Carbon\Carbon($scheduler->date_end))->format('d/m/Y') : '') }}"/>
		</label>

		@if ($errors->has('date_end'))
		<span class="msg error">
			<strong>{{ $errors->first('date_end') }}</strong>
		</span>
		@endif
	</div>
	<div class="form-field">
		<label>Descripción:
			<input type="text" class="{{ $errors->has('description') ? 'error' : '' }}" name="description" value="{{ (old('description')) ? old('description') : ((isset($scheduler)) ? $scheduler->description : '') }}" required/>
		</label>

		@if ($errors->has('description'))
		<span class="msg error">
			<strong>{{ $errors->first('description') }}</strong>
		</span>
		@endif
	</div>
	<div class="form-field">
		<label>Aforo máximo de reservas:
			<input type="number" class="{{ $errors->has('capacity') ? 'error' : '' }}" name="capacity" value="{{ (old('capacity')) ? old('capacity') : ((isset($scheduler)) ? $scheduler->capacity : '25') }}" min="25" max="400" required/>
		</label>

		@if ($errors->has('capacity'))
		<span class="msg error">
			<strong>{{ $errors->first('capacity') }}</strong>
		</span>
		@endif
	</div>
	<div class="form-field">
		<label>Tiempo medio clientes (min.):
			<input type="number" class="{{ $errors->has('average_time') ? 'error' : '' }}" name="average_time" value="{{ (old('average_time')) ? old('average_time') : ((isset($scheduler)) ? $scheduler->average_time : '30') }}" min="30" max="180" step="30" required/>
		</label>

		@if ($errors->has('average_time'))
		<span class="msg error">
			<strong>{{ $errors->first('average_time') }}</strong>
		</span>
		@endif
	</div>
</div>
<div class="foot">
	<button type="submit" class="button success">
		Guardar
	</button>
</div>
{{ Form::close() }}

@push('styles')
<link rel="stylesheet" type="text/css" href="/manager/css/melon.datepicker.css"/>
@endpush

@push('scripts')
<script type="text/javascript" src="/manager/js/moment-with-locales.js"></script>
<script type="text/javascript">
	$("input[name='date_start'], input[name='date_end']").datepicker({
		beforeShow: function() {
			$(this).datepicker("widget").wrap('<div class="ll-skin-melon"></div>');
		},
		onClose: function() {
			$(this).datepicker("widget").hide();
			$(this).datepicker("widget").unwrap();
		}
	});

	update_min_end();

	function update_min_end(){
		var min_date = ($("input[name='date_start']").val().trim() != "") ? moment($("input[name='date_start']").val(), "DD/MM/YYYY", true).add(1, 'd').toDate() : new Date();

		$("input[name='date_end']").datepicker("option", "minDate", min_date);
	}

	$("input[name='date_start']").datepicker("option", "onSelect", function(dateText) {
		update_min_end();
	});
</script>
@endpush
@endsection

resources/views/restaurant/schedulers/organize.blade.php
@extends('layouts.restaurant')

@section('main_content')
@php ($role = Auth::guard()->user()->hasRoleAt($restaurant->id))

<h4>Horario "{{$scheduler->description}}"</h4>
<div id="organizeScheduler" @if($role == 'A')class="editable" @endif></div>

@push('styles')
<link rel="stylesheet" type="text/css" href="/manager/css/fullcalendar.min.css"/>
<link rel="stylesheet" type="text/css" href="/manager/css/scheduler.min.css"/>
@endpush

@push('scripts')
<script type="text/javascript" src="/manager/js/moment-with-locales.js"></script>
<script type="text/javascript" src="/manager/js/fullcalendar.min.js"></script>
<script type="text/javascript" src="/manager/js/scheduler.min.js"></script>
<script type="text/javascript" src="/manager/js/horario_scheduler.js"></script>
<script type="text/javascript">
	var sch_days = {!! json_encode($scheduler_days) !!};

	$('#organizeScheduler').fullCalendar('renderEvents', sch_days, true);

	@if($role == 'A')
	function create_day(week_day, start, end){
		loader_bar(true);

		var id = "{!! $restaurant->id.'_'.$scheduler->id.'_' !!}"+Math.floor(Math.random()*2000);

		var myEvent = {
			id:id,
			start: start,
			end: end,
			resourceId:week_day
		};

		$('#organizeScheduler').fullCalendar('renderEvent', myEvent, true);

		var data = {
			"sch_day_hour_start": start.format('HH:mm:ss'),
			"sch_day_hour_end": end.format('HH:mm:ss'),
			"sch_day_week_day": week_day,
			"sch_day_code": id,
		};

		$.ajax({
			type: "POST",
			url: "{!! route('restaurant.schedulers.ajax.sch_day.create', [$restaurant->id, $scheduler->id]) !!}",
			data: data,
		}).done(function(msg) {
			console.info('Created event!');
		}).fail(function(jqXHR, textStatus) {
			console.error(textStatus, jqXHR);
			$('#organizeScheduler').fullCalendar('removeEvents',id);
		}).then(function(){
			loader_bar(false);
		});
	};

	function update_day(code, week_day, start, end, revert){
		loader_bar(true);

		var data = {
			"sch_day_hour_start": start.format('HH:mm:ss'),
			"sch_day_hour_end": end.format('HH:mm:ss'),
			"sch_day_week_day": week_day,
			"sch_day_code": code,
		};

		$.ajax({
			type: "POST",
			url: "{!! route('restaurant.schedulers.ajax.sch_day.update', [$restaurant->id, $scheduler->id]) !!}",
			data: data,
		}).done(function(msg) {
			console.info('Updated event!');
		}).fail(function(jqXHR, textStatus) {
			console.error(textStatus, jqXHR);
			revert();
		}).then(function(){
			loader_bar(false);
		});
	}

	function remove_day(code){
		loader_bar(true);

		$.ajax({
			type: "POST",
			url: "{!! route('restaurant.schedulers.ajax.sch_day.remove', [$restaurant->id, $scheduler->id]) !!}",
			data: {
				"sch_day_code": code
			},
		}).done(function(msg) {
			console.info('Deleted event!');
			$('#organizeScheduler').fullCalendar('removeEvents',code);
		}).fail(function(jqXHR, textStatus) {
			console.error(textStatus, jqXHR);
		}).then(function(){
			loader_bar(false);
		});
	}
	@endif
</script>
@endpush

@endsection